### ISSUE TITLE
Bug: can't combine filtering and attribute value array creation with no object wrapper

### ISSUE THREAD

**Issue by elimisteve** [sanity-io/groq-js#14]
To reproduce:

1. Visit https://groq.dev/4927196f-b502-4a75-a962-39c6dcc2e4ef
2. Replace middle textarea's content with this text:

```
// Works
*[completed == true]{title}

// Works
//*[].title

// But combining them doesn't work
//*[completed == true].title
```

3. Uncomment each of the 3 examples in turn (and comment out the one above it)

4. You'll see that `*[completed == true].title` results in `null` rather than a populated array of strings that are the titles of completed tasks.

**Comment by elimisteve** [comment]
Similar example from the [cheat sheet](https://www.sanity.io/docs/query-cheat-sheet):

> // Return an array of attribute values (no object wrapper)
> *[_type == 'movie'].title

**Comment by elimisteve** [comment]
I also want to say that GROQ is brilliantly designed! Designing any kind of technology to be both simple and powerful is _extraordinarily_ hard, but you've done it.

Bravo! :tada:

**Comment by judofyr** [comment]
The correct way of combining this is:

```
*[completed == true][].title
```

You can read this as:

- `*`: Fetch all documents
- `[completed == true]`: Filter by `completed`
- `[]`: For each element …
- `.title`: access the `title` field.


The reason why `*[completed == true].title` doesn't work is because it attempts to access the `title` field from the array, but an array doesn't have any fields. The reason why `*[completed == true]{title}` works is because `{}` is a bit special: When the left-side is an array it will iterate over all of the elements and process the projection per element.

Now, for some "historical" context: In Sanity.io today `*[completed == true].title` actually works. The initial semantics of `.title` was to behave like `{}` and support both arrays and objects. This turns out to complicate things a lot when it comes to nested projections (e.g. in `*[_type == "person"]{"a": a.foo}` it behaves differently if `a` is an array or an object) which is hard to both implement correctly and efficiently. By requiring `[]` before any "array field accesses" it's much easier to implement and it's easier for the user to see what's going on. Now when you see `a.foo` you know that `a` is a plain object, and if you see `a[].foo` you know that `a` is an array.

groq-js implements the new, improved semantics which are described in [the spec](http://github.com/sanity-io/GROQ). Sanity.io doesn't yet fully support the new semantics. This is both because it takes a while to implement it properly, and because we need to figure out how to roll it out since there are some breaking changes.

In the future we will have groq-js and Sanity.io fully aligned!

**Comment by judofyr** [comment]
> I also want to say that GROQ is brilliantly designed! Designing any kind of technology to be both simple and powerful is _extraordinarily_ hard, but you've done it.
> 
> Bravo! 🎉

Thanks! This means a lot! 😄

**Comment by elimisteve** [comment]
@judofyr Hey again! Is Glush open source? I'm about to start an ambitious cross-language translation project and I would _love_ to use Glush; it seems better than anything else out there, AFAICT.

**Comment by elimisteve** [comment]
Closing issue, and my unrelated comment ^^right there^^ has been ~moved to https://github.com/judofyr/glush/pull/2#issuecomment-636440694
